eureka:
  instance:https://github.com/RamazanAbdurahmanov/ff-ms-config-server/tree/main
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
